apiVersion: v1
kind: Service
metadata:
  name: postgres-slave-svc
spec:
  type: LoadBalancer
  selector:
    component: postgres-slave
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
