apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-slave
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: postgre-storage
  resources:
    requests:
      storage: 1Gi