kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgre-storage
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain   # Retain or Delete
volumeBindingMode: WaitForFirstConsumer   # WaitForFirstConsumer or Immediate
allowVolumeExpansion: true    # true or false
parameters:
  storageaccounttype: Standard_LRS   # Premium or Standard
  kind: Managed